project:
  type: website

website:
  title: "Pipe Break Prediction Report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-prep.qmd
        text: Data Prep
      - href: eda.qmd
        text: EDA
      - href: modeling.qmd
        text: Modeling
      - href: results.qmd
        text: Results

format:
  html:
    theme: cosmo
    toc: true


