project:
  type: book

book:
  title: "Predicting Water Main Breaks with Machine Learning"
  author: "Brice Nelson"
  date: "2025-05-12"
  chapters:
    - index.qmd
    - executive-summary.qmd
    - introduction.qmd
    - problem-statement.qmd
    - data-exploration.qmd
    - methodology.qmd
    - model-development.qmd
    - results.qmd
    - discussion.qmd
    - conclusion.qmd
    - future-work.qmd
    - references.qmd
    - appendix.qmd

format:
  html:
    theme: cosmo
    number-sections: true
